---
version: "3.8"
services:
  movies:
    image: savyadugyala09/moviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: savyadugyala09/trainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: savyadugyala09/rechargerepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: savyadugyala09/dthrepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
